services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_ENV: "production"
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: database
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_KEY: ${JWT_KEY}
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - ordent

  database:
      image: postgres:13
      environment:
        POSTGRES_USER: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PORT: ${POSTGRES_PORT}
      restart: unless-stopped
      networks:
        - ordent
      volumes:
        - postgres-data:/var/lib/postgresql/data

networks:
  ordent:
    driver: bridge

volumes:
  postgres-data: